#!/usr/bin/env bash
#  Script bash gives you information about the holbertonschool file
if [ -e Bestschool ]
then
    echo "school file exists"
    if [ -s Bestschool ]
    then
echo "school file is not empty"
    else
echo "school file is empty"
    fi
    if [ -f Bestschool ]
    then
echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
